rootcolor=10140fff

bordercolor=42493fff

focuscolor=255022ff

maximizescreencolor=baccb3ff

urgentcolor=ffb4abff

scratchpadcolor=a0cfd3ff

globalcolor=3c4b38ff

overlaycolor=1e4d51ff

jump_hit_fg_color=d6e8ceff

jump_hit_bg_color=e0e4daff

jump_hit_border_color=a2d398ff
