rootcolor=0e1513ff
bordercolor=3f4945ff
focuscolor=005143ff
maximizescreencolor=b1ccc3ff
urgentcolor=ffb4abff
scratchpadcolor=aacbe3ff
globalcolor=334b45ff
overlaycolor=2a4a5fff

jump_label_decorate_fg_color=85d6c1ff
jump_label_decorate_bg_color=334b45ff
jump_label_decorate_focus_fg_color=dee4e0ff
jump_label_decorate_focus_bg_color=cde8dfff
jump_label_decorate_border_color=85d6c1ff
