rootcolor=14140cff

bordercolor=47473bff

focuscolor=464a02ff

maximizescreencolor=c8c9a6ff

urgentcolor=ffb4abff

scratchpadcolor=a3d0bfff

globalcolor=47482eff

overlaycolor=244e41ff

jump_hit_fg_color=e5e5c0ff

jump_hit_bg_color=e5e3d6ff

jump_hit_border_color=c7cc79ff
