# Import
source=~/.config/mango/binds.conf
source=~/.config/mango/input.conf
source=~/.config/mango/rules.conf
source=~/.config/mango/theme.conf
source=~/.config/mango/colors.conf
source=~/.config/mango/layouts.conf


# Monitors
allow_tearing=1

# Desktop
#monitorrule=name:^DVI-D-1$,width:1600,height:900,refresh:60,x:0,y:180
#monitorrule=name:^HDMI-A-1$,width:1920,height:1080,refresh:75,x:1600,y:0

# Victus Laptop
monitorrule=name:eDP-1,width:1920,height:1080,refresh:144,x:0,y:0


# Autostart
exec-once = waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css
exec-once = awww-daemon
exec-once = awww img /home/astosolo/Pictures/Wallpapers/wallhaven-jevdow.png
exec-once = /usr/lib/xdg-desktop-portal-wlr

exec-once=wl-paste --watch cliphist store

